In [2]:
# pip install numpy

# Importing Numpy

import numpy as np


In [4]:
# Creating 0-D array (That is also know as Scalar Array)

import numpy as np
arr1=np.array(5)
arr1

array(5)

In [3]:
import numpy as np
arr1=np.array(5)
print(arr1)

5


In [7]:
# Creating 1-D Array

import numpy as np
arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
# Finding a Dimensional Of Array

import numpy as np
arr=np.array([1,2,3,4,5])

print(arr.ndim)

1


In [14]:
# Creating 2-D Array

a=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)  # We can alse specify the data types ( int and float)
print(a)
a

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [22]:
# Creating 2-D Array and changing the data type.

a=np.array([[1,2,3,4],[5,6,7,8]],dtype=int)  # We can alse specify the data types ( int and float)
a

#print(a.ndim)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# Creating 3-Dimensional Array

c=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(c)

print()

print("It is used to help a find a number of arrays :",c.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

It is used to help a find a number of arrays : 3


In [31]:
# Defining number of dimension.

import numpy as np
x=np.array([1,2,3,4], ndim=3)
x

TypeError: array() got an unexpected keyword argument 'ndim'

In [34]:
# Creating array of Zero

x=np.zeros((2,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


In [37]:
x=np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# Creating a array of Ones

x=np.ones([3,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [40]:
# Eye function :  Returns array filled with zeros except in the diagonal,whose values are equal to :

a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [44]:
a=np.eye(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [46]:
a=np.eye(2,3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0]])

In [49]:
a=np.eye(4,k=-1,dtype=int)
a

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [50]:
a=np.eye(5,k=-2,dtype=int)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [52]:
a=np.eye(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Accessing array elements

In [2]:
# Accessing 1-D array

import numpy as np

a=np.array([10,20,30,40,50])
print(a[0])

10


In [7]:

a=np.array([10,20,30,40,50])
print(a[0])
print(a[1])
print(a[2])
print(a[3])

print()

[print("Adding a value using index position :",a[0]+a[1])]

10
20
30
40

Adding a value using index position : 30


[None]

In [11]:
# Accessing 2-D Array

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,2])

print("Number of Arrays :",a.ndim)

8
Number of Arrays : 2


In [16]:
# Access 3-D Array

c=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])

print(c[1,1,2])

print("Number of array :",c.ndim)

12
Number of array : 3


In [18]:
# negative Indexing

a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a[0,-3])

3


# Slicing Array

In [19]:
a=np.array([10,20,30,40,50,60,70,80,90])

print(a[0:3])
print(a[2:])
print(a[:5])
print(a[-4:-1])
print(a[1:5:2])
print(a[::3])
print(a[::1])
print(a[::-1])

[10 20 30]
[30 40 50 60 70 80 90]
[10 20 30 40 50]
[60 70 80]
[20 40]
[10 40 70]
[10 20 30 40 50 60 70 80 90]
[90 80 70 60 50 40 30 20 10]


In [20]:
# Slicing 2-D Array

a=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(a[1,1:4])

[7 8 9]


In [23]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(a[0:2, 2])
# print(a[0:2, 1:4])

[3 8]


In [22]:
print(a[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types

In [ ]:
"""
        i-integer
        b-boolean
        u-unsigned integer
        f-float
        c-complex float
        m
        M-datetime
        O-object
        S-string
        U-unicode string
        v-
"""

# Finding dtypes of array

In [3]:
import numpy as np

a=np.array([1,2,3,4])

print(a)

print(a.dtype)

[1 2 3 4]
int32


In [5]:
# Create an array with data type string.

a=np.array([1,2,3,4],dtype='S')
print(a)

print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
# Change data type from floot to interger by using int as parameter value

a=np.array([1.1,2.2,3.3,4.4,5.5,0.0])
b=a.astype(int)
print(b)
print(b.dtype)

print()

c=b.astype(bool)
print(c)
print(c.dtype)

[1 2 3 4 5 0]
int32

[ True  True  True  True  True False]
bool


In [9]:
# Copy to the array

x=np.array([1,2,3,4,5])  # Value is changed in x .Doesn't change in y
y=x.copy()

x[0]=42

print(x)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
# View is just a view of the original array

x=np.array([1,2,3,4,5,6])
y=x.view()

x[0]=53

print(x)
print(y)

[53  2  3  4  5  6]
[53  2  3  4  5  6]


# Shape of an Array

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

(2, 4)


# Reshapping means changing the shape of an Array

In [20]:
# Reshape from 1-D to 2-D

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

b=a.reshape(4,3)

print(b)

print()

print(b.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

2


In [24]:
# Reshape from 1-D to 3-D

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

b=a.reshape(2,3,2)

print(b)

print('Total Number of arrays :',b.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Total Number of arrays : 3


# Flatting Array

In [26]:
# Flattening array means converting a Multidimensional array into a 1D array.

In [29]:
a=np.array([[1,2,3,4],[5,6,7,8]])

b=a.reshape(-1)

print(b)

[1 2 3 4 5 6 7 8]


# Iterating Arrays

In [30]:
# Iterating means going through elements one by one.

In [31]:
# Iterating 1-D Array

a=np.array([1,2,3])

for i in a:
    print(i)

1
2
3


In [32]:
# Iterating 2-D Array

a=np.array([[1,2,3,4],[5,6,7,8]])

for i in a:
    print(i)
    
    for j in i:
        print(j)

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [33]:
# Iterating 2-D Array

a=np.array([[1,2,3,4],[5,6,7,8]])

for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


In [35]:
# Iterating 3-D Array

a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [1]:
# Iterating 3-D Array using nditer

import numpy as np

a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for i in np.nditer(a):
    print(i)


1
2
3
4
5
6
7
8
9


In [38]:
# Iterate through every scalar element of the 2D array skipping 1 element.

a=np.array([[1,2,3,4],[5,6,7,8]])

for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8


In [2]:
# Iterate through every scalar element of the 2D array skipping 1 element.

a=np.array([[1,2,3,4],[5,6,7,8]])

for i in np.nditer(a[:,::2]):
    print(i)

1
3
5
7


In [5]:
# Enumerator 1-D Array

import numpy as np

x=np.array([10,20,30])

for index ,i in np.ndenumerate(x):
    print(index,i)

(0,) 10
(1,) 20
(2,) 30


In [7]:
# Enumerate 2D Array

x=np.array([[1,2,3,4],[5,6,7,8]])

for index,i in np.ndenumerate(x):
    print(index,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Numpy Array

In [9]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

z=np.concatenate((x,y))

print(z)


[1 2 3 4 5 6 7 8]


In [17]:
 # Joining two 2-D arrays along rows (axis=1)
    
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[1,2,3,4],[5,6,7,8]])
    
z=np.concatenate((x,y),axis=1)  #  (axis 1) It's represents print a row wise
    
print(z)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [18]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([[1,2,3,4],[5,6,7,8]])
    
z=np.concatenate((x,y),axis=0)  #  (axis 0) It's represents print a column wise
    
print(z)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


# Stacking Arrays

In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.stack((a,b),axis=1)
print(c)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [23]:
# Stacking along Rows

a=np.array([1,2,3])

b=np.array([4,5,6])

c=np.hstack((a,b))

print(c)

[1 2 3 4 5 6]


In [28]:
# Stacking along Columns

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.vstack((a,b))
print(c)



[[1 2 3 4]
 [5 6 7 8]]


In [27]:
# Stacking along Height/Depth

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.dstack((a,b))

print(c)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Splitting NnumPy Arrays

In [30]:
a=np.array([1,2,3,4,5,6,7,8])

aa=np.array_split(a,3)  # If it has less element it will create blank array.

print(aa)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [31]:
a=np.array([1,2,3,4,5,6,7,8])

aa=np.array_split(a,4)  # If it has less element it will create blank array.

print(aa)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [32]:
print(aa[0])
print(aa[1])
print(aa[2])

[1 2]
[3 4]
[5 6]


In [33]:
#Split the 2-D array 

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1= np.array_split(a,4)
print(a1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [34]:
#Split the 2-D array along rows

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1= np.array_split(a,4,axis=1)
print(a1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [36]:
#Split the 2-D array along rows or horizontal

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1= np.hsplit(a,3)
print(a1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Array

In [38]:
x=np.array([1,2,3,4,5,4,3,6,7,8])

# Element 4 is in the three index position 

x1=np.where(x==4)

print(x1)

(array([3, 5], dtype=int64),)


In [41]:
# finding the element in even Indices

x=np.array([1,2,3,4,5,6,7,8])

# Display the elements in the index position 0,2,4,6

x1=np.where(x%2==0)

print("Even Numbers Position :",x1)

Even Numbers Position : (array([1, 3, 5, 7], dtype=int64),)


In [40]:
# Finding the element in Odd Indicies

a=np.array([1,2,3,4,5,6,7,8,9])

# Display the Odd numbers

aa=np.where(x%2==1)

print("Odd Numbers Position :",aa)

Odd Numbers : (array([0, 2, 4, 6], dtype=int64),)


# String the array

In [44]:
arr=np.array([50,90,80,65,35])
print(np.sort(arr))      # Uing the sort the Array

[35 50 65 80 90]


In [45]:
# Strings are sorted Alphabetically

a=np.array(['Python','Csharp','DataScience','Machine Learning','Artificial Intellgience'])

a1=np.sort(a)

print(a1)

['Artificial Intellgience' 'Csharp' 'DataScience' 'Machine Learning'
 'Python']


In [46]:
# Boolean are sorted false as first

arr=np.array([True,False,True,True,False])

print(np.sort(arr))

[False False  True  True  True]


In [70]:
# Sort a 2-D Array

a=np.array([[1,3,2],[8,9,5]])
aa=np.sort(a)
print(aa)

[[1 2 3]
 [5 8 9]]


# LINEAR ALGEBRA

# Dot Product of the two Arrays

In [68]:
x=np.array([[1,2],[4,5]])

y=np.array([[7,8],[10,12]])

z=np.dot(x,y)

print(z)

[[27 32]
 [78 92]]


In [69]:
x = np.array([[1,2],[3,4]]) 
y = np.array([[5,6],[7,8]]) 

z=np.dot(x,y)

print("Martices :",z)

Martices : [[19 22]
 [43 50]]


# Dot product of the two vectors

In [72]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

np.vdot(x,y)

70

In [73]:
x=np.array([[1,2],[3,4]])
print(x)

print()

y=np.array([[5,6],[7,8]])
print(y)

print()

print('Inner Product :')
print(np.inner(x,y))


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

Inner Product :
[[17 23]
 [39 53]]


# Inverse of a matrix

In [79]:
x=np.array([[1,2],[4,5]])
y=np.linalg.inv(x)

print(y)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


# Determinant of Matrix

In [81]:
# Determinant [[a,b],[c,d]] = 'ad-bc'

a=np.array([[1,2],[5,6]])

a1=np.linalg.det(a)

print(a1)

-3.999999999999999


In [82]:
round(np.linalg.det(a))

-4

In [94]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

b1=np.linalg.det(b)

print(b1)


6.66133814775094e-16


In [97]:
print("Round value is :",round(np.linalg.det(b)))

Round value is : 0


In [89]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.linalg.det(b)
print(a)

print()

print("Round value is :",round(np.linalg.det(b)))

6.66133814775094e-16

Round value is : 0


In [98]:
round(np.linalg.det(b))   (Doubt)

0

# Solve Linear Equation using NumPy

In [100]:
a=np.array([[3,1],[1,2]])

b=np.array([9,8])

np.linalg.solve(a,b)

array([2., 3.])

# Statistical Function

In [103]:
# Finding minimum and max value element in an array

a=np.array([[1,2,3],[10,23,12],[7,8,9]])

print(a)

print()

print("Lowest value :",np.amin(a))

print()

print("Highest value :",np.amax(a))

[[ 1  2  3]
 [10 23 12]
 [ 7  8  9]]

Lowest value : 1

Highest value : 23


In [104]:
# Mean-sum of all elements divided by the no of elements

a=np.array([10,20,30,40])

print(np.mean(a))

25.0


In [105]:
# Median - Middle element if no of elements are Odds 

a=np.array([10,20,50])
print(np.median(a))

20.0


In [106]:
# Median - Middle element if no of elements are Even

a=np.array([10,20,50,30])
print(np.median(a))

25.0


In [107]:
# Standard Deviation Formula - 1.Calculate mean  2.Std Deviation

a=np.array([1,2,3,4,5])

print(a)

print()

print("Standard Deviation Formula :",np.std(a))

[1 2 3 4 5]

Standard Deviation Formula : 1.4142135623730951


In [108]:
# Varience Formula

a=np.array([1,2,3])
print(a)

print()

print(np.var(a))

[1 2 3]

0.6666666666666666


In [110]:
# Average - Also same as mean

a=np.array([5,6,7])
print(a)

print()

print("Average value is :",np.average(a))

[5 6 7]

Average value is : 6.0


In [115]:
# Percentile Function :describes the value that a given percent of the values are lower than.

a = np.array([2,10,20,56,34,90,78,98,32])  
print(a)  

print()

print("Show a  Percentage value :",np.percentile(a,50))

[ 2 10 20 56 34 90 78 98 32]

Show a  Percentage value : 34.0


In [116]:
#Peak-to-Peak Function: determine the range of values along an axis.

a = np.array([[20,10,30],[6,7,34]])  
print(np.ptp(a,0))

[14  3  4]
